name: Testing

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:

  run-tests:
    name: Run Tests
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'

      - name: Run Tests
        run: go test ./...
